# Basic Site Settings
title: "Junk Store"
email: "junkstore@sdk.co.nz"
description: "Play non-Steam games on your Steam Deck with ease."
baseurl: "" # root
url: "https://www.junkstore.xyz" # your real live URL

# Theme Settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "default" # Default skin (we will set light/dark below)
locale: "en-US"

# Light/Dark Mode
# Allow user to switch between light and dark themes (Auto)
# Can force if you want to (ask me)
minimal_mistakes_skin: "dark"
# Add "skin" toggle automatically:
skin_toggle: true

# Site-Wide Open Graph Image (for social previews)
og_image: /assets/images/junkstore-og-banner.png # <--- you need to upload this file!

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate

# Markdown and Kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections
collections:
  tutorials:
    output: true
    permalink: /:path/
  troubleshooting:
    output: true
    permalink: /:path/
  pages:
    output: true
    permalink: /:path/


# Categories
jekyll-archives:
  enabled:
    - categories
  layout: category
  permalinks:
    category: /:path/:name/


# Author/Social Links
#author:
#  name: "Junk Store Team"
#  email: "junkstore@sdk.co.nz"
#  links:
#    - label: "Email"
#      icon: "fas fa-fw fa-envelope"
#      url: "mailto:junkstore@sdk.co.nz"
#    - label: "Reddit"
#      icon: "fab fa-fw fa-reddit"
#      url: "https://www.reddit.com/r/JunkStore"
#    - label: "Discord"
#      icon: "fab fa-fw fa-discord"
#      url: "https://discord.gg/your-invite"
#    - label: "GitHub Decky Plugin"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/ebenbruyns/junkstore"
#    - label: "GitHub Closed Source Version"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/your-closed-source-repo"
#    - label: "Mastodon"
#      icon: "fab fa-fw fa-mastodon"
#      url: "https://mastodon.social/@junkstore"
#    - label: "Bluesky"
#      icon: "fab fa-fw fa-cloud"
#      url: "https://bsky.app/profile/junkstore.xyz"
#    - label: "X (Twitter)"
#      icon: "fab fa-fw fa-x-twitter"
#      url: "https://x.com/junkstore"
#    - label: "Facebook"
#      icon: "fab fa-fw fa-facebook"
#      url: "https://facebook.com/junkstore"

# Footer Links (can match author)
footer:
  links:
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/r/JunkStore"
      target: "_blank"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/6mRUhR6Teh"
      target: "_blank"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@JunkStore"
      target: "_blank"
    - label: "Bluesky"
      icon: "fab fa-fw fa-cloud"
      url: "https://bsky.app/profile/junkstore.bsky.social"
      target: "_blank"
    - label: "X (Twitter)"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/JunkStore4deck"
      target: "_blank"
    - label: "Privacy Policy"
     # icon: "fab fa-fw fa-github"
      url: "/privacy-policy"
   # - label: "GitHub Closed Source"
      #icon: "fab fa-fw fa-github"
     # url: "https://github.com/your-closed-source-repo"

# SEO/Analytics
# google_analytics: # Optional
# bing_site_verification:   # Optional
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-E2Y00GCMSG"   # Replace with your GA4 measurement ID
    anonymize_ip: true            # Optional

# Permalinks
permalink: /:categories/:title/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Static asset caching for performance
# These headers will be set by GitHub Pages or can be configured in hosting
staticfiles:
  - /assets/images/
  - /assets/css/
  - /assets/js/

# Output
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - test
  - docs
keep_files:
  - .git

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

navigation:
  main: main
  sidebar: sidebar-sample

logo: "/assets/images/JSAvatar-44.webp"

# Site search functionality
search: true
lunr:
  search_within_pages: true

enable_copy_code_button: true

google_analytics:
  id: "G-E2Y00GCMSG" # replace with your actual Google Analytics Measurement ID

# Footer scripts (loads after main analytics)
after_footer_scripts:
  - /assets/js/conversion-tracking.js